name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Buildozer
        uses: Peter-Smyth/buildozer-action@v1
        with:
          buildozer_version: master
          
