name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: Luka967/buildozer-action@v1.2.2
        with:
          buildozer_version: master
          
